version: '3.9'

services:
  web:
    build: .
    command: python src/main.py
    restart: always
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    expose:
      - 8080
    env_file:
      - .env
    networks:
      - elk
    depends_on:
      - elasticsearch
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    expose:
      - 6379

  elasticsearch:
    image: bitnami/elasticsearch
    volumes:
      - elasticsearch_data:/bitnami/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    expose:
      - 9200
    environment:
      - ELASTIC_VERSION=8.10.4
      - xpack.security.enabled=false
      - discovery.type=single-node
      - network.host=0.0.0.0
      - http.port=9200
    networks:
      - elk
    restart: unless-stopped

  kibana:
    image: bitnami/kibana
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: unless-stopped

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local
